[package]
name = "hdfs"
version = "0.0.1"
authors = [ "Hyunsik Choi <hyunsik.choi@gmail.com>" ]
build = "build.rs"

[lib]
name = "hdfs"
path = "src/lib.rs"

[dependencies]
log = "0.3.1"
url = "0.2.31"

[build-dependencies]
gcc = "0.3.5"